name: mypipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: second step
        run: |
           echo "Hello from second step"
           sleep 10
      - name: third step
        run: |
           touch kaish.txt
           ls -l
           sleep 10
